services:
  server:
    image: project1-server  # ← ИЗМЕНИТЬ: build на image
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ../database.db:/app/database.db
      - ../photo:/app/photo
      - ../sh:/app/sh
      - ../back:/app/back
    environment:
      - NODE_ENV=production
      - TZ=Europe/Moscow 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--max-time", "10", "-f", "http://localhost:${PORT}"]
      interval: 30s  # ← ИЗМЕНИТЬ: с 1s на 30s
      timeout: 10s
      retries: 3     # ← ИЗМЕНИТЬ: с 1 на 3
      start_period: 40s
    env_file:
      - .env

  bot:
    image: project1-bot  # ← ИЗМЕНИТЬ: build на image
    volumes:
      - ../bot:/app
    environment:
      - API_BASE_URL=http://server:${PORT}
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env